Cleaned TLTestProject
added two exceptions: TestLinkException and MissingPermission exception,
thrown when encountering a general TestLinkAPI error and when missing
permissions to do an action respectively. Removed
NoSuchTestSuiteException: Instead of throwing an exception, such methods
should just return an empty Optional (no exceptions because of user
error!)